# -*- coding: utf-8 -*-
"""Layer-1 curated data, part D: how a real lab behaves.

This is the layer that makes a virtual lab feel like a lab rather than a calculator:
bottle strengths, how each standard solution is actually made and standardised, the
salt-analysis decision tree, indicator tables, GHS codes, incompatibilities, waste,
what to do in an emergency, and the list of things the app deliberately refuses.
"""

# ------------------------------------------------------------------ stock bottles
# What a bottle says when you pick it up. The engine uses these to convert a volume
# you pour into moles, and to compute the molarity of a "dilute" you make from it.
STOCK_BOTTLES = [
 # label, contents species id, %w/w, density, molarity, prep/notes
 ("Hydrochloric acid, concentrated", "hcl", 37.0, 1.19, 12.1, "constant-boiling azeotrope 20.2 %; the 37 % strength loses HCl on every opening, so a 1 M made from it is only 1 M 'to 2 %' until standardised against Na2CO3"),
 ("Sulphuric acid, concentrated", "h2so4", 98.0, 1.84, 18.4, "hygroscopic; the bottle gets HEAVIER on the shelf, not lighter"),
 ("Nitric acid, concentrated", "hno3", 69.5, 1.42, 15.8, "fumes and yellows with light as NO2 dissolves; keep in amber"),
 ("Ammonia solution 'sp. gr. 0.880'", "nh4oh", 35.0, 0.88, 18.0, "the 0.880 label is a density, not a concentration - the classic first-year confusion"),
 ("Sodium hydroxide pellets", "naoh", None, None, None, "assay about 96-98 % with 2-4 % carbonate; a '0.1 M NaOH' made by weighing pellets is wrong until you standardise it and correct for carbonate"),
 ("Potassium hydrogen phthalate (primary standard)", "khp", None, None, None, "KHP: 204.22 g/mol, dried at 110 C, standardises NaOH to 0.1 % - the reason NaOH is never a primary standard"),
 ("Anhydrous sodium carbonate (primary standard)", "na2co3", None, None, None, "105.99 g/mol, dry at 270-300 C not above (it starts losing CO2); the acidimetric standard"),
 ("Oxalic acid dihydrate", "oxalicacid", None, None, None, "126.07 g/mol; can be weighed directly, unlike KMnO4 - so it is the standard that standards permanganate"),
 ("Sodium thiosulphate pentahydrate", "na2s2o3", None, None, None, "248.18 g/mol; the crystals effloresce, so make it in boiled-and-cooled water with a pinch of Na2CO3 and standardise after a week"),
 ("Potassium permanganate", "kmno4", None, None, None, "never a primary standard - it always carries MnO2, which photodecomposes more of it; boil, keep 2 days in the dark, filter through glass wool, then standardise on oxalate"),
 ("Silver nitrate, 0.05 M", "agno3aq", None, None, 0.05, "8.4935 g/L; amber bottle; it stains skin black because light reduces it to silver metal"),
 ("EDTA disodium dihydrate, 0.01 M", "na2edta", None, None, 0.01, "3.7224 g/L; can be made by weighing directly (a genuine primary standard for complexometry)"),
 ("Sulphuric acid 1 M (for permanganate work)", "h2so4", 5.0, 1.03, 1.0, "always acidify with H2SO4 - HCl is oxidised by permanganate and HNO3 pre-oxidises your Fe2+"),
 ("Universal indicator solution", "universalind", None, None, None, "about 0.04 % each of methyl orange, methyl red, bromothymol blue and phenolphthalein in ethanol/water - that is why the sequence of colours is what it is"),
 ("Phenolphthalein indicator", "phenolphthalein", None, None, None, "1 % w/v in 50 % ethanol; two drops per 100 mL; a pink that fades within 30 s means the CO2 of the air got in - a real, common 'failed end point'"),
 ("Methyl orange indicator", "methyleorange", None, None, None, "0.1 % in water; do not use it for a weak-acid titration - its range (3.1-4.4) is nowhere near the basic end point"),
 ("Lime water, saturated", "limewater", None, None, None, "about 1.7 g/L at 20 C and LESS as it warms (retrograde solubility); a fresh solution must be decanted off the crust, and it never lasts more than a week open"),
 ("Barium chloride solution, 5 %", "bacl2aq", None, None, 0.2, "the sulphate reagent; acidify the test solution with dilute HCl first or a sulphite/carbonate false-positive appears"),
 ("Hydrogen peroxide 20 volume", "h2o2", 6.0, 1.03, 1.94, "'20 volume' means 20 L of O2 from 1 L of solution; ~1.94 M and it halves in activity in a warm cupboard in a month"),
 ("Bromine water, saturated", "br2water", 3.0, None, None, "shake liquid bromine with water; the aqueous layer is decanted - and this bottle must be stoppered and kept cool or the lab smells for a week"),
 ("Iodine solution (Lugol)", "i2_soln", 5.0, None, 0.2, "5 g I2 + 10 g KI per 100 mL; the KI is not a catalyst, it is the solvent (I3-); amber bottle"),
 ("Sodium sulphite solution (fresh)", "naso3aq", None, None, 0.5, "make from the solid just before use; on air it becomes sulphate and the SO2 generation stops working, which is the #1 'my reagent is dead' report"),
 ("Tollens' reagent (make fresh, use at once)", "agno3aq", None, None, None, "to 2 mL of 0.05 M AgNO3 add NaOH to precipitate the oxide, then NH3 dropwise just until it dissolves; NEVER store - ammoniacal silver deposits explosive Ag3N on standing"),
 ("Fehling's A and B", "cuso4aq", None, None, None, "A: 34.6 g/L CuSO4.5H2O. B: 173 g/L potassium sodium tartrate + 70 g/L NaOH. Mix equal volumes at the moment of use - that is why it is two bottles"),
 ("Benedict's reagent", "cuso4aq", None, None, None, "17.3 g/L CuSO4.5H2O + 100 g/L sodium carbonate + 173 g/L sodium citrate; alkaline citrate instead of tartrate, so it is stable and can be stored in one bottle"),
 ("Soda lime", "sodalime", None, None, None, "NaOH about 4 % + CaO 94 % with a water indicator; absorbs CO2 and dries; the CO2 absorbent of every respiration experiment"),
 ("Silica gel, blue indicating", "sio2gel", None, None, None, "CoCl2-doped; regenerate at 120 C until blue; about 5 g of gel takes up ~1 mL of water"),
 ("Concentrated hydrochloric acid, 2 M (working)", "hcl", 2.0, 1.01, 2.0, "dilute the concentrated bottle 1:6, not 1:5 - the arithmetic students get wrong is the dilution factor, not the equation"),
]

# ---------------------------------------------------------------- indicator reference
INDICATORS = [
 # name, pH lo, pH hi, colour_acid, colour_base, hex_acid, hex_base, use/note
 ("Thymol blue (1st range)", 1.2, 2.8, "red", "yellow", "#D01F1F", "#F2D000", "for strong acid against carbonate-free base"),
 ("Methyl orange", 3.1, 4.4, "red", "yellow", "#D01F1F", "#F2D000", "strong acid vs weak base (NH4OH); NOT for acetic acid vs NaOH"),
 ("Bromophenol blue", 3.0, 4.6, "yellow", "blue-purple", "#F2D000", "#2E3192", "cheap and sharp"),
 ("Methyl red", 4.4, 6.2, "red", "yellow", "#D01F1F", "#F2D000", "the best single indicator for a weak acid titrated with a strong base only if you correct for the 0.1 pH shift"),
 ("Litmus", 4.5, 8.3, "red", "blue", "#D01F1F", "#2C6FBB", "the teaching indicator; useless for precision, superb for 'is it acidic at all'"),
 ("Bromothymol blue", 6.0, 7.6, "yellow", "blue", "#F2D000", "#2C6FBB", "the neutral-range indicator; for CO2-in-water and respiration experiments"),
 ("Phenol red", 6.8, 8.4, "yellow", "red", "#F2D000", "#D21F3C", "cell-culture medium colour; the same chemistry as the milk-souring demo"),
 ("Neutral red", 6.8, 8.0, "red", "yellow", "#D01F1F", "#F2D000", "vital stain in biology, so a shared bottle between departments"),
 ("Naphtholphthalein", 7.3, 8.7, "colourless", "green", "#FFFFFF", "#2FA65B", "sharper than phenolphthalein for carbonate titrations"),
 ("Phenolphthalein", 8.2, 10.0, "colourless", "pink-magenta", "#FFFFFF", "#EE9AAE", "the standard for weak acid/strong base; in >12 M base the pink FADES to colourless (carbinol) - an observation that has wasted a thousand student hours"),
 ("Thymolphthalein", 9.3, 10.5, "colourless", "blue", "#FFFFFF", "#2C6FBB", "for carbonate-free hydroxide titrations"),
 ("Alizarin yellow R", 10.1, 12.0, "yellow", "violet-red", "#F2D000", "#8B0000", "the only usable one above pH 11"),
 ("Eriochrome Black T", 6.3, 11.5, "red-wine (metal complex)", "blue (free)", "#722F35", "#1F3FBF", "complexometric: the metal-indicator complex is wine red and EDTA steals the metal to give blue; needs pH 10 buffer"),
 ("Murexide", 9.0, 11.0, "yellow", "violet", "#F2D000", "#8B5FC9", "calcium at pH 12 (the Mg is already precipitated and cannot interfere)"),
 ("Calcon / Eriochrome Blue Black R", 12.0, 12.5, "red", "blue", "#D01F1F", "#2C6FBB", "calcium with EDTA at high pH"),
 ("Fluorescein (adsorption indicator)", None, None, "green fluorescence", "pink precipitate surface", "#37C55A", "#EE9AAE", "Fajans chloride titration - the precipitate surface changes colour, not the solution"),
 ("Potassium chromate (Mohr)", None, None, "yellow", "brick-red ppt", "#F2D000", "#B33A1A", "not a pH indicator at all: it is the end-point PRECIPITATE for AgNO3 vs chloride"),
 ("Diphenylamine", None, None, "colourless", "violet-blue", "#FFFFFF", "#4A3FA8", "redox (dichromate/permanganate) in sulfuric acid; destroyed by excess oxidiser, so add it in excess too"),
 ("Ferroin", None, None, "pale blue (Fe3+ form)", "red-orange (Fe2+ form)", "#5D7FB8", "#E4571B", "the Ce4+/Fe2+ and dichromate titration indicator; E0' = 1.06 V"),
 ("Starch", None, None, "colourless", "blue-black", "#FFFFFF", "#101B3A", "with I2/I3- only; add near the end point of an iodine titration - too early the complex is slow to release iodine and you overshoot; hot starch stops working"),
]

# ------------------------------------------------------------- paper / strip tests
PAPER_TESTS = [
 ("red litmus", "dip or touch with a glass rod", "turns blue above pH about 8.3", "the only test a beginner needs for a base"),
 ("blue litmus", "as above", "turns red below pH about 4.5", "and for ammonia gas it must be DAMP"),
 ("universal / pH paper", "touch, do not dip into the sample", "0.5-1 pH unit; a dipped strip leaches dye into your solution", "for quantitative work use a meter; for 'is it 2 or is it 6' the paper is faster"),
 ("starch-iodide paper", "hold at the mouth of the tube, or wet it and use as a spot plate", "blue-black with any oxidiser that frees iodine: Cl2, Br2, NO2, O3, H2O2, Fe3+, MnO4-, NO2-", "a positive does NOT mean chlorine - that is the exam trap"),
 ("lead acetate paper", "hang at the mouth of the reaction vessel", "brown to black with H2S or any soluble sulphide", "and the black stain can be 'restored' by a drop of H2O2 (PbS -> PbSO4), a nice self-check"),
 ("acidified potassium dichromate paper", "wet with dilute H2SO4 first", "orange to green with a reducing gas (SO2, H2S)", "the discriminator between SO2 and CO2, which limewater cannot separate"),
 ("magnesium oxide / 'burning splint'", "for O2 and N2 discrimination", "relights for O2; extinguishes for CO2 and N2", "and NO browns at the mouth - always note WHICH of these you used"),
 ("cobalt chloride paper", "dry, and kept in a stoppered tube", "blue to pink with water", "the water test that is not copper sulphate, and it regenerates in a warm oven"),
 ("turmeric paper", "dip and dry", "brown to red-brown with a borate; the colour goes green with ammonia fumes", "rosocyanine - the only borate test that needs no special reagent"),
 ("ginger/guaiac paper", "for oxidising agents", "blue with H2O2 + peroxidase", "old-fashioned but a real enzyme demonstration"),
]

# --------------------------------------------------------- cation analysis (the tree)
# Each group: reagent, condition, what precipitates, what stays, the separation logic,
# and the confirmatory tests the engine can drive as a flow chart.
CATION_SCHEME = {
 "group 0 (ammonium)": {
   "reagent": "NaOH solution, warm; then Nessler's reagent on a spot",
   "precipitate": None,
   "gas": "NH3 (pungent, turns damp red litmus blue, white fumes with HCl)",
   "why": "must come FIRST because every later group reagent is ammoniacal - a solution that was never tested for NH4+ cannot be reported as NH4+-free",
   "confirm": ["NH3 + damp red litmus -> blue", "Nessler: yellow-brown (iodide of Millon's base)", "HCl rod: dense white fumes"]},
 "group I (lead, mercury(I), silver)": {
   "reagent": "dilute HCl, cold, in the presence of a little excess acid",
   "precipitate": {"PbCl2": "white needles, soluble in hot water", "Hg2Cl2": "white, turns black with NH3", "AgCl": "white curdy, soluble in NH3 then reprecipitated by HNO3"},
   "why": "Ksp: AgCl 1.8e-10, PbCl2 1.7e-5 (but 3x more soluble hot), Hg2Cl2 1.4e-18 - the only chlorides that are insoluble enough to fall in 0.3 M HCl",
   "separation": "boil the residue with water: PbCl2 dissolves (confirm with K2CrO4 -> yellow PbCrO4); the residue goes to NH3 for silver vs mercury",
   "gotcha": "an excess of HCl redissolves PbCl2 as [PbCl4]2-, and too little HCl leaves BiOCl/SbOCl basic salts which look exactly like a group-I precipitate"},
 "group II (Cu, Cd, Bi, Hg, As, Sb, Sn)": {
   "reagent": "H2S (or 5 % thioacetamide, 80 C) in 0.3 M HCl",
   "precipitate": {"CuS": "black", "PbS": "black", "CdS": "yellow", "Bi2S3": "black-brown", "HgS": "black", "As2S3": "yellow", "Sb2S3": "orange", "SnS2": "yellow"},
   "why": "in 0.3 M acid [S2-] is about 1e-22 M, so Q exceeds Ksp only for the truly insoluble sulphides - ZnS (2e-25), MnS, NiS, CoS all stay in solution",
   "separation": "IIA dissolves in yellow ammonium polysulphide (As, Sb, Sn thio-salts); IIB (Cu, Cd, Bi, Pb, Hg) does not",
   "gotcha": "the classic error is adding the H2S before the acid, so zinc and nickel come down with everything and the whole scheme collapses"},
 "group III (Fe, Al, Cr)": {
   "reagent": "NH4Cl (solid, dissolved) then NH4OH to ammonia smell, warm",
   "precipitate": {"Fe(OH)3": "red-brown gelatinous", "Al(OH)3": "white gelatinous", "Cr(OH)3": "grey-green gelatinous"},
   "why": "the buffer holds [OH-] near 1e-5 M: enough for Al(OH)3 (3e-34) and Fe(OH)3 (2.8e-39) to precipitate quantitatively but not Mg(OH)2 (5.6e-12), and Zn/Ni/Co stay as their ammine complexes",
   "separation": "dissolve the residue in NaOH: Al(OH)3 and Cr(OH)3 go into solution (aluminate, chromite), Fe(OH)3 does not - the split",
   "gotcha": "if you skip NH4Cl the OH- is high enough that magnesium precipitates too; and any phosphate present drags everything down as phosphates"},
 "group IV (Zn, Mn, Ni, Co)": {
   "reagent": "H2S in ammoniacal solution (after group III is filtered off)",
   "precipitate": {"ZnS": "white", "MnS": "flesh-pink", "NiS": "black", "CoS": "black-brown"},
   "why": "at pH 9 [S2-] rises by about ten orders of magnitude, so the more soluble sulphides can now exceed their Ksp - the SAME reagent as group II, only a different pH, which is the entire teaching value of this scheme",
   "separation": "dissolve in dilute HCl (ZnS, MnS dissolve; NiS/CoS, once 'aged', refuse) and re-precipitate",
   "gotcha": "NiS and CoS go 'insoluble' if they are boiled too long - the old saying 'a precipitate that has aged is a precipitate you cannot redissolve' is a real crystallographic ageing effect, not superstition"},
 "group V (Ba, Sr, Ca)": {
   "reagent": "(NH4)2CO3 in NH4Cl/NH3, warm 60 C",
   "precipitate": {"BaCO3": "white", "SrCO3": "white", "CaCO3": "white crystalline"},
   "why": "carbonates of the alkaline earths are all far below Ksp; magnesium stays because MgCO3 needs higher [CO3^2-] and MgNH4PO4 needs phosphate, absent here",
   "separation": "acetic acid dissolves all three; then K2CrO4 precipitates Ba (yellow BaCrO4, insoluble in acetic acid), NH4OH reprecipitates Sr and Ca... standard split: Ba with chromate, Sr with CaSO4/acetone, Ca with ammonium oxalate",
   "gotcha": "if phosphate was not removed at group III the whole group V is a false positive"},
 "group VI (Mg, Na, K, NH4 leftover)": {
   "reagent": "no group reagent - identify individually",
   "precipitate": {"MgNH4PO4": "white crystalline with sodium phosphate + NH3"},
   "why": "sodium and potassium have no common insoluble salt worth precipitating, so these are flame and specific-reagent ions",
   "confirm": {"Mg2+": "white ppt with Na2HPO4 in ammoniacal solution", "Na+": "persistent yellow flame; uranyl magnesium acetate -> pale yellow crystals", "K+": "lilac flame through cobalt glass; sodium cobaltinitrite -> yellow ppt", "NH4+": "as group 0"},
 },
}

ANION_SCHEME = {
 "dilute H2SO4 tests": {
   "carbonate": "brisk effervescence, gas clouds limewater (and the milkiness redissolves on excess)",
   "sulphite": "pungent SO2, decolourises acidified KMnO4 and turns dichromate paper green",
   "sulphide": "rotten-egg gas, blackens lead acetate paper",
   "nitrate": "nothing cold; on warming with Cu turnings, brown NO2 fumes",
   "halide": "HCl: white fumes only; HBr: orange-brown Br2 (acid fumes); HI: violet I2 plus black solid and H2S smell",
   "acetate": "the ester smell with a drop of ethanol and warm acid"},
 "concentrated H2SO4 + MnO2 / dry tests": {
   "nitrate": "brown NO2 with concentrated H2SO4 on the solid, and the brown ring with FeSO4",
   "chloride": "greenish-yellow Cl2 which whitens starch-iodide paper",
   "iodide": "violet vapour; plus H2S and the black solid - iodide reduces the acid",
   "oxalate": "CO and CO2 - the gas burns blue and clouds limewater",
   "tartrate": "the burnt-sugar smell of pyruvic aldehyde",
   "borate": "the green-edged flame with ethanol and acid (turmeric test as backup)"},
 "solution tests": {
   "sulphate": "white BaSO4, insoluble in concentrated HCl",
   "phosphate": "yellow (NH4)3PO4.12MoO3 with ammonium molybdate in HNO3, on warming",
   "chromate/dichromate": "yellow with Ba2+ in neutral; the acidified dichromate + H2O2/ether blue (CrO5) is the specific test",
   "thiosulphate": "acid gives a yellow sulfur cloud + SO2 smell; and it decolourises iodine without the starch colour ever appearing",
   "fluoride": "etches glass - the only school-relevant 'test' that destroys its own apparatus, so the sim runs it as the 'silicic acid' tube",
   "iodide": "blue-black with chloramine-water in the right excess (the Schumberger test)",
   "bromide/iodide (after the group)": "chloroform layer colours after adding chlorine water in excess: bromine orange -> iodine violet -> colourless as the iodine is oxidised to iodate",
 },
}

ORGANIC_FUNCTIONAL_TESTS = [
 # functional group, reagent, positive observation, timescale, false positives / notes
 ("alkene / alkyne", "bromine water (in CCl4 for teaching)", "orange-yellow discharged, no HBr fumes", "seconds", "phenols, anilines, aldehydes and enols also decolourise - so run it with the litmus test for HBr"),
 ("alkene / alkyne", "cold dilute alkaline KMnO4 (Baeyer)", "purple to brown MnO2", "seconds", "same interferences; formic acid, SO2 and reducing sugars all respond"),
 ("aromatic ring", "combustion on a spatula", "smoky yellow flame", "instant", "the carbon percentage is the explanation; not a specific test"),
 ("haloalkane", "alcoholic AgNO3, then dilute HNO3", "AgX curds: white (Cl), cream (Br), yellow (I); rate: tertiary > secondary > primary", "10 s to 5 min", "the rate IS the mechanism (SN1) - the app should let the student predict before it runs"),
 ("alcohol (1st/2nd/3rd)", "Lucas reagent (HCl/ZnCl2)", "cloudiness: tertiary at once, secondary 5 min, primary none", "0-10 min", "only valid for C<=6 alcohols; longer chains are insoluble anyway and look 'positive'"),
 ("alcohol (1st/2nd)", "acidified K2Cr2O7, warm", "orange to green", "1-2 min", "tertiary alcohols give nothing, which is the classification; aldehydes and phenols also reduce it"),
 ("alcohol (polyol)", "Cu(OH)2 then NaOH", "deep-blue clear solution", "instant", "glycerol, sugars, tartarate all positive - a 'multiple OH on adjacent carbons' test"),
 ("aldehyde", "Tollens' reagent, warm in a water bath", "silver mirror or grey-black precipitate", "2-5 min", "reducing sugars, formic acid, alpha-hydroxy ketones are also positive; the reagent must be made and destroyed the same day"),
 ("aldehyde", "Fehling / Benedict, boil", "blue to brick-red Cu2O", "1-3 min", "ketoses are positive too (enediol rearrangement) - which is the most commonly mis-taught 'specific' test in chemistry"),
 ("aldehyde", "Schiff's reagent", "magenta", "1 min", "SO2 gives a false magenta that acid destroys; formalin gives a blue-white product, not magenta"),
 ("methyl ketone / ethanol", "iodine in KI + NaOH, warm", "yellow CHI3 flakes with an antiseptic smell", "5 min", "acetaldehyde, propan-2-ol, lactic acid and pyruvic acid all positive - it tests CH3CO-, not a functional group"),
 ("carboxylic acid", "NaHCO3 solution", "brisk CO2 effervescence", "instant", "the one clear difference from phenol; stronger-than-carbonic acids only"),
 ("carboxylic acid", "litmus + pH", "pH about 2.4-3 for 0.1 M", "instant", "and the ester smell with ethanol and a drop of acid confirms it"),
 ("ester", "hydroxamic acid test (NH2OH/FeCl3)", "burgundy-red ferric hydroxamate", "1 min", "the general test for esters and anhydrides, far better than the smell"),
 ("phenol", "neutral FeCl3 solution", "violet (blue/green depending on the phenol)", "instant", "enols and some carboxylates colour too; and salicylic acid gives violet-red, aspirin nothing - the reaction that grades your own synthesis"),
 ("phenol", "bromine water", "decolourised + white precipitate of 2,4,6-tribromophenol", "instant", "far more sensitive than litmus for phenol in water"),
 ("primary amine", "carbylamine (CHCl3 + alcoholic KOH)", "the most unpleasant smell in the syllabus", "5 min", " demonstration only, in a hood; no other class responds"),
 ("amine (any)", "HNO2 (NaNO2 + dilute HCl, 0-5 C)", "primary aliphatic: N2 effervescence; aromatic: diazonium which couples to an orange azo dye; secondary: yellow oil; tertiary: no reaction", "instant-5 min", "the single best class-separation reaction, and the reason the temperature is in the procedure"),
 ("amide / urea", "NaOH then warm, or biuret", "NH3 smell for amides; violet with CuSO4/NaOH for biuret (and proteins)", "2 min", "the biuret reaction counts peptide bonds, so free amino acids give nothing"),
 ("nitro compound", "Zn dust + NaOH, then acetaldehyde?", "no - the correct test is reduction to the amine then the carbylamine/azo route", "-", "kept as a 'the textbook test you should distrust' record"),
 ("alkyl halide (Beilstein)", "copper wire in a flame", "green-edged flame from volatile copper halides", "instant", "positive for F too, and for many nitrogen compounds - a screening test, not an identification"),
 ("starch", "iodine in KI", "blue-black", "instant", "and the colour vanishes hot and returns cold - the reversibility is the whole point of the iodine-clock variant"),
 ("reducing sugar", "Benedict, boil", "the green-yellow-orange-red ladder = concentration", "3 min", "non-reducing sucrose needs an acid hydrolysis step and neutralisation first"),
 ("lipid", "grease spot on paper; Sudan III in alcohol", "translucent permanent spot; red stain", "instant", "the spot does not dry out, which is how you exclude water"),
 ("protein", "xanthoproteic (HNO3 then NH3)", "yellow to orange", "1 min", "aromatic residues only - gelatin is a famous false negative"),
 ("protein", "biuret (NaOH + 1 % CuSO4)", "violet", "instant", "needs two or more peptide bonds"),
 ("protein", "Millon's reagent, warm", "brick-red", "5 min", "tyrosine only; and the reagent is mercurous/nitric acid, so it is a demonstration"),
]

# ------------------------------------------------------------------------------- GHS
GHS_PICTOGRAMS = {
 "flame": "GHS02 flammable", "flame-over-circle": "GHS03 oxidising", "exploding-bomb": "GHS01 explosive",
 "gas-cylinder": "GHS04 gas under pressure", "corrosion": "GHS05 corrosive",
 "skull-crossbones": "GHS06 acute toxicity", "health-hazard": "GHS08 serious health hazard",
 "environment": "GHS09 environmental hazard", "exclamation-mark": "GHS07 irritant/harmful",
}
H_CODES = {
 "H200": "Unstable explosive", "H201": "Explosive; mass explosion hazard",
 "H220": "Extremely flammable gas", "H224": "Extremely flammable liquid and vapour",
 "H225": "Highly flammable liquid and vapour", "H226": "Flammable liquid and vapour",
 "H240": "Heating may cause an explosion", "H241": "Heating may cause a fire or explosion",
 "H250": "Catches fire spontaneously on contact with air",
 "H251": "Self-heating; may catch fire", "H260": "In contact with water releases flammable gases which may ignite spontaneously",
 "H270": "May cause or intensify fire; oxidiser", "H271": "May cause fire or explosion; strong oxidiser",
 "H280": "Contains gas under pressure; may explode if heated",
 "H290": "May be corrosive to metals", "H300": "Fatal if swallowed",
 "H301": "Toxic if swallowed", "H302": "Harmful if swallowed",
 "H310": "Fatal in contact with skin", "H311": "Toxic in contact with skin",
 "H312": "Harmful in contact with skin", "H314": "Causes severe skin burns and eye damage",
 "H315": "Causes skin irritation", "H317": "May cause an allergic skin reaction",
 "H318": "Causes serious eye damage", "H319": "Causes serious eye irritation",
 "H330": "Fatal if inhaled", "H331": "Toxic if inhaled", "H332": "Harmful if inhaled",
 "H334": "May cause allergy or asthma symptoms or breathing difficulties if inhaled",
 "H335": "May cause respiratory irritation", "H340": "May cause genetic defects",
 "H350": "May cause cancer", "H350i": "May cause cancer by inhalation",
 "H360": "May damage fertility or the unborn child", "H370": "Causes damage to organs",
 "H372": "Causes damage to organs through prolonged or repeated exposure",
 "H373": "May cause damage to organs through prolonged or repeated exposure",
 "H400": "Very toxic to aquatic life", "H401": "Toxic to aquatic life",
 "H410": "Very toxic to aquatic life with long lasting effects",
 "H411": "Toxic to aquatic life with long lasting effects",
 "H420": "Harms public health and the environment by destroying ozone",
}
P_CODES = {
 "P201": "Obtain special instructions before use", "P210": "Keep away from heat, hot surfaces, sparks and open flame; no smoking",
 "P220": "Keep/storage away from combustible materials", "P221": "Take any precaution to avoid mixing with combustibles",
 "P230": "Keep wetted with ...", "P231": "Keep under ...", "P232": "Protect from moisture",
 "P240": "Ground and bond container and receiving equipment",
 "P241": "Use explosion-proof electrical/ventilating/lighting equipment",
 "P243": "Take precautions against static discharges", "P260": "Do not breathe dust/fume/gas/mist/vapours/spray",
 "P264": "Wash hands thoroughly after handling", "P270": "Do not eat, drink or smoke when using this product",
 "P271": "Use only outdoors or in a well-ventilated area", "P273": "Avoid release to the environment",
 "P280": "Wear protective gloves/protective clothing/eye protection/face protection",
 "P301+P310": "IF SWALLOWED: immediately call a POISON CENTRE/doctor",
 "P302+P352": "IF ON SKIN: wash with plenty of soap and water",
 "P303+P361+P353": "IF ON SKIN (or hair): remove/take off all contaminated clothing; rinse skin with water",
 "P305+P351+P338": "IF IN EYES: rinse cautiously with water for several minutes; remove contact lenses if present and easy; continue rinsing",
 "P310": "Immediately call a POISON CENTRE or doctor", "P312": "Call a POISON CENTRE/doctor if you feel unwell",
 "P330": "Rinse mouth", "P333+P313": "If skin irritation or rash occurs: get medical attention",
 "P363": "Wash contaminated clothing before reuse", "P370+P378": "In case of fire: use ... to extinguish",
 "P391": "Contain spillage", "P403+P233": "Store in a well-ventilated place; keep container tightly closed",
 "P405": "Store under lock", "P406": "Store in a corrosive-resistant container lined with inert material",
 "P410+P403": "Protect from sunlight; store in a well-ventilated place",
 "P501": "Dispose of contents/container to ...",
}

# --------------------------------------------------------- incompatibility matrix
MIXING_RULES = [
 # a, b, severity, what happens, action
 ("bleach", "acid (any: HCl, vinegar, H2SO4)", "critical", "chlorine and, at higher pH, chloramine gas evolve; in a small unventilated bathroom this is a real hospitalisation cause", "refuse and explain"),
 ("bleach", "ammonia or ammonium salts", "critical", "chloramines (NH2Cl, NHCl2) - coughing, pulmonary oedema at high dose", "refuse and explain"),
 ("bleach", "hydrogen peroxide", "warn", "vigorous oxygen evolution; the bottle can blow its cap off", "allow only vented, small scale"),
 ("acid", "cyanide (any, including 'refined' silver-plating salts)", "critical", "HCN gas; fatal within minutes in a closed room", "block - no cyanide bottle exists in the app"),
 ("concentrated sulfuric acid", "water", "critical", "local boiling throws acid out of the vessel", "allow only as 'acid into water, slowly, stirred'"),
 ("permanganate or chlorate or nitrate (dry oxidiser)", "glycerol, sugar, glycol, sawdust, sulfur", "critical", "spontaneous fire or explosion, often a second after mixing", "block; show the reaction as a demonstration record only"),
 ("sodium or potassium metal", "water in a closed vessel", "critical", "hydrogen plus heat inside a closed vessel is a bomb", "block; open trough, pea-sized piece only"),
 ("ammonium nitrate", "heat in quantity, confined", "critical", "runaway decomposition and detonation (this is how industrial ammonium-nitrate accidents happen)", "block; small-scale open-tube only, display"),
 ("aluminium or zinc powder", "acid in a closed vessel", "critical", "hydrogen pressure plus exotherm", "never closed"),
 ("chlorine gas", "ammonia or hydrogen in light", "warn", "nitrogen trichloride / explosive combination", "ventilate, keep sources apart"),
 ("mercury (spilled)", "vacuum cleaner or heat", "warn", "mercury vapour is the hazard, not the beads", "spill procedure instead"),
 ("hydrofluoric acid (any)", "glass", "warn", "the container is destroyed and the acid is then in the wrong place", "plastic vessel only, calcium gluconate on the bench"),
 ("hypochlorite", "acetone or any ketone", "warn", "chloroform and explosive chlorinated byproducts", "refuse"),
 ("concentrated nitric acid", "organic solvent (acetone, alcohol, ether, glycerol)", "critical", "nitration/oxidation runaway, sometimes ignition", "block; only with the hood flag and gram-scale"),
 ("silver nitrate", "skin or organic matter plus light", "info", "black silver stains that take a week to grow off", "warn and let it happen - a realistic consequence is a good teacher"),
 ("ammonia solution", "silver nitrate in excess, stored", "critical", "silver nitride / fulminating silver forms on standing and detonates", "make fresh, destroy same day - the app enforces 'no storage'"),
 ("bromine", "ammonia", "critical", "nitrogen tribromide", "refuse"),
 ("carbon disulfide", "any warm surface or sodium hydroxide on a hot plate", "critical", "autoignition near 90 C; the lowest of any common lab liquid", "block"),
 ("phosphorus (white)", "air", "critical", "ignites at about 30 C and the burns are deep and systemic-poisoning risks", "not in the app at all - only the historical record"),
 ("sodium peroxide or sodium superoxide", "water or CO2 (breath)", "warn", "vigorous O2 evolution with heat; ignites organics", "hood, tiny scale"),
 ("silicon tetrachloride or phosphorus chlorides", "water", "warn", "HCl fumes and pressure in a closed vessel", "hood, open vessel"),
 ("hydrogen sulphide (from FeS or thioacetamide)", "an unvented bench", "critical", "the odour is lost within minutes as the olfactory nerve is desensitised - 'I can't smell it' is the danger sign", "hood or don't run it"),
 ("lead or barium soluble salts", "anything you might drink/eat", "critical", "cumulative heavy-metal poisoning; soluble barium is deadly at 0.2-0.5 g", "gloves, no mouth pipetting, and the app prints this whenever such a salt is opened"),
]

# ------------------------------------------------------------- the refusal list
# Every entry is a real thing a curious person might type into a chemistry app.
# The app must not silently do nothing - it explains what it will and won't simulate.
BLOCKED = [
 ("synthesis of explosives", "TATP, nitroglycerin, picric acid, fulminating silver, chlorates with fuel",
  "Blocked. Not because a phone can't display it, but because the only thing an app adds over a textbook here is a step-by-step recipe with quantities and a 'run again' button.",
  "The reaction itself, its energetics and its accident history are in the safety records - that's the teachable part."),
 ("cyanide chemistry", "HCN generation, K/Na cyanide bottles, silver cyanide plating baths",
  "Blocked. Acidifying any cyanide salt in an unventilated room is a death, and home users do have 'silver dip' and 'gold dip' in a drawer.",
  "The cyanide-ion test chemistry (Prussian blue) is shown descriptively as reference with the hazard numbers."),
 ("controlled-substance synthesis", "any route to a scheduled drug, including the 'harmless' precursors",
  "Blocked.", "Pharmacology and detection chemistry are described as data, not as a procedure."),
 ("mustard gas / nerve-agent chemistry", "thiodiglycol, phosphonofluoridates, dimethyl methylphosphonate routes",
  "Blocked completely.", "Not a school experiment, not a home experiment, not a thing an app should help with even in a 'theoretical' mode."),
 ("mercury and lead preparations", "distilling mercury, preparing organomercurials, dissolving lead in a kitchen pot",
  "Blocked at quantity; the properties/hazard pages exist.", "Cumulative poisons, and the exposure route people forget is vapour and dust, not skin."),
 ("white phosphorus and its compounds", "P4 handling, phosphine generation from CaC2 impurity",
  "Blocked.", "Red phosphorus is present as data with the oxidiser warning."),
 ("carbon monoxide in an enclosed space", "any CO generation without a hood or outdoors",
  "Blocked; CO from a formic-acid/S-h2so4 train is a standard demo but not in a bedroom.", "The gas tests and the toxicology are in the record."),
 ("hydrogen in a sealed vessel with a flame", "the classic 'explode a bottle with H2' video",
  "Warn + require an open-vessel choice.", "The squeaky pop is a detonation in miniature; the app should say so rather than pretend otherwise."),
]

# ------------------------------------------------------------------- waste classes
WASTE_CLASSES = {
 "halogenated organic": {"items": ["CHCl3", "CCl4", "CH2Cl2", "chlorobenzene"], "rule": "never down the drain; a separate labelled drum - incineration is the only route", "why": "ozone-depleting and/or persistent, and they partition into your body fat"},
 "non-halogenated organic": {"items": ["acetone", "ethanol", "toluene", "ether", "hexane", "ethyl acetate"], "rule": "flammable-solvent waste drum, no more than 5 L in the room, away from oxidisers", "why": "vapour heavier than air travels to a flame across the floor"},
 "heavy metal (Cr, Pb, Cd, Hg, Ba)": {"rule": "collect, never pour out; a licensed carrier; soluble barium and all chromium(VI) are the acute ones", "why": "Pb/Cd/Hg are cumulative; Cr(VI) is a carcinogen by inhalation and a corrosive by contact"},
 "cyanide / sulfide residues": {"rule": "keep alkaline, never mix with acid waste, hand to the collector", "why": "acid contact releases HCN or H2S in the waste bottle itself"},
 "acids and alkalis (aqueous)": {"rule": "dilute to under 1 M and flush with 20 volumes of water only where local rules allow; otherwise neutralise to pH 6-8 with carbonate, not with the other concentrated bottle", "why": "the heat of neutralisation in a small waste jug can crack it"},
 "oxidiser solids (permanganate, dichromate, chlorate, nitrate)": {"rule": "keep in a labelled jar, never in a drawer with organics, no paper padding", "why": "the oxidiser waste incident is the most common serious lab fire"},
 "broken glass / sharps": {"rule": "rigid box, not the bin; pipettes tip-first", "why": "the injury is in the bin bag, not in the beaker"},
 "reactive metals (Na, K, Li, Mg powder, Al powder)": {"rule": "quench by dissolving in isopropanol, then ethanol, then water - in that order, outdoors", "why": "dropping sodium into water is the funniest thing until the piece is bigger than you thought"},
 "mercury spill": {"rule": "ventilate, collect beads with card + tape or zinc foil/amalgam, dust with sulfur, never a vacuum cleaner, never a floor drain", "why": "the vapour is the poison and a vacuum is a mercury-vapour generator"},
}
STORAGE_RULES = [
 ("corrosive-acid cabinet", "acids together, but nitric acid on its own shelf - nitric fumes attack every other bottle and can start a fire in an organic one"),
 ("flammables cabinet", "solvents only, metal bin, no fridge unless it is an explosion-rated one (a domestic fridge has a spark every time the thermostat cycles)"),
 ("oxidiser shelf", "away from any fuel and from the acid cabinet; ammonium nitrate and permanganate not in the same cupboard"),
 ("light-sensitive (amber bottles)", "AgNO3, Hg2(NO3)2, KMnO4, H2O2 (vented cap), chlorine water, Fe(III) oxalate"),
 ("hygroscopic / CO2-absorbing", "NaOH, KOH, CaCl2, P2O5, conc H2SO4, CaO - all with tight caps and dated"),
 ("base cabinet", "ammonia separate from acids across the room, not on the same shelf - the white NH4Cl dust will cover everything"),
 ("gas cylinders", "chained upright, cap on when not in use, fuel gas and oxygen separated by a distance or a barrier"),
 ("the fridge question", "nothing volatile and nothing food-labelled in the same fridge as anything you intend to eat"),
]

# --------------------------------------------------------------- emergency protocol
EMERGENCY = {
 "acid or alkali in the eye": "Immediately at the eye wash: hold the lids open with your fingers, flush for a FULL 15 minutes, then a doctor. Neutralising is wrong - it adds a second burn and heat. Blink while flushing and move the eye side to side.",
 "acid on the skin": "Flood with water for 15-20 minutes while removing clothing/jewellery. For hydrofluoric acid: keep flushing and get calcium gluconate gel on it, then an emergency department even if it does not hurt yet (HF burns are delayed by hours and destroy bone).",
 "phenol on the skin": "Do not just use water - phenol is only sparingly soluble. Wash with PEG 300 or glycerol, then lots of water, then medical attention; it is absorbed and systematically toxic.",
 "bromine on the skin": "Water 15 min, then a paste of glycerol or sodium thiosulphate/bicarbonate; do not cover it airtight.",
 "alkali burn": "Water longer than you think (20 min); the slipperiness is saponified skin, not the alkali itself, so the burn is deeper than it looks.",
 "mercury spill": "Evacuate unnecessary people, open a window, no vacuum, no broom, collect with card/tape, sulfur or zinc-foil afterwards, and put the waste in a sealed jar with water on top.",
 "fire in a beaker": "Cover with a watch glass or beaker larger than it - cut the air. Do NOT carry a burning vessel to a sink. Use a fire blanket, then a CO2/dry-powder extinguisher; sodium and metal fires need dry sand or class-D, never water or CO2.",
 "solvent fire on a person": "Stop, drop and roll, then the blanket; remove contaminated clothing (it keeps burning against skin) and cool the burn with water for 20 min.",
 "inhalation of fumes": "Out into fresh air immediately, sit upright, and for chlorine/phosgene/NO2 even a 'fine' period of a few hours can precede delayed pulmonary oedema - so medical observation is the correct action, not a cup of tea.",
 "ingestion": "Do not induce vomiting for corrosives or hydrocarbons. Rinse mouth, small sips of water, phone the poison centre with the bottle in your hand. Have the label photographed before you need it.",
 "the glass-cut-and-bleeding-first-aid": "Let it bleed a little under running water to flush fragments, no sucking, cover with a dressing and press; a deep hand cut near a tendon needs a surgeon within hours.",
}

# --------------------------------------------------------------------- curriculum
# Each experiment maps to reaction ids so a student following a board's practical
# list can find exactly what the sim will run, with apparatus and time.
CURRICULUM = {
 "CBSE Class 11": {
   "Determination of melting point of an organic substance / boiling point of a liquid": {"react": ["eq_hydrate_ind"], "app": ["thiele-tube","capillary-tubes"], "time": 20, "note": "a 1-2 C range means a pure sample; a broad low range means an impurity"},
   "Verify the effect of concentration on reaction rate (sodium thiosulphate and H2SO4)": {"react": ["redox_thio_acid_clock","kin_thio_time"], "app": ["conical","white-paper-cross","stopwatch"], "time": 40},
   "Study the effect of temperature on reaction rate (sodium thiosulphate and H2SO4)": {"react": ["kin_thio_temp"], "time": 45},
   "Study the effect of a catalyst (KMnO4 and oxalic acid with/without MnSO4)": {"react": ["redox_oxalate_kmno4"], "time": 40},
   "Prepare a pure, dry sample of sodium chloride from sodium hydrogencarbonate": {"react": ["syn_znso4","ab_hcl_nahco3"], "time": 40},
   "Titrate the acid/base (HCl vs NaOH with phenolphthalein and methyl orange)": {"react": ["ab_hcl_naoh","ab_hcl_nh4oh"], "app": ["burette_50","conical_250"], "time": 60},
   "Determine enthalpy of neutralisation / enthalpy of solution of copper sulphate": {"react": ["therm_neutralisation_pair","therm_crystallisation_water"], "app": ["thermometer_bei","polystyrene-cup"], "time": 45},
   "Observe diffusion in water with KMnO4 crystals / rate of diffusion with HCl and NH3": {"react": ["syn_nh4cl"], "time": 25},
   "Identify the ions present in the given given samples (unknown salts)": {"react": ["grp1_agcl","an_co3","an_so4","flame_na","flame_cu"], "time": 90},
   "Study the shifts in equilibrium with common ions / Le Chatelier with dichromate": {"react": ["flame_chromate_dichromate","eq_common_ion_agcl","equ_no2_syringe"], "time": 30},
   "Chemical kinetics: order with respect to a reactant (iodine clock)": {"react": ["redox_iodine_clock","kin_hypo_kinetics_iodine"], "time": 60},
 },
 "CBSE Class 12": {
   "Kinetics of the reaction between potassium permanganate and oxalic acid": {"react": ["redox_oxalate_kmno4"], "time": 60, "note": "plot [oxalic] against t; the curve is sigmoid because Mn2+ autocatalyses"},
   "Preparation of solutions: molarity and ppm (glucose/detergent)": {"react": [], "app": ["volumetric_100","balance_ana"], "time": 40},
   "Determine the rate constant of hydrolysis of an ester (ethyl acetate with water, conductometric or titrimetric)": {"react": ["org_hydrolysis_ester"], "time": 90},
   "Study effect of concentration on the rate of reaction between sodium thiosulphate and H2SO4": {"react": ["kin_thio_time"], "time": 40},
   "Surface chemistry: adsorption of acetic acid on activated charcoal (or dye)": {"react": [], "time": 60},
   "Colloids: preparation of Fe(OH)3 and starch sols, Tyndall, coagulation": {"react": ["ppt_feoh3","ppt_fecns"], "time": 60},
   "Chemical kinetics: the iodine clock reaction": {"react": ["redox_iodine_clock"], "time": 40},
   "Electrochemistry: verify the Nernst equation with a Daniell cell / EMF of cells": {"react": ["elec_daniell","elec_daniel_conc"], "app": ["voltmeter","salt-bridge"], "time": 45},
   "Determine the concentration of the unknown solution of potassium chloride/sodium chloride using a conductometer": {"react": ["elec_conductivity","app_conductometric_titr"], "time": 45},
   "Study corrosion and the prevention thereof (sacrificial protection)": {"react": ["elec_corrosion","elec_galvanise"], "time": 30},
   "Chemistry in everyday life: water hardness by EDTA / soap consumption": {"react": ["redox_edta_hardness","app_hard_water_test","ppt_soap_scum"], "time": 60},
   "Determine dissolved oxygen in water (Winkler)": {"react": ["env_do_winkler"], "time": 90},
   "Titration of Fe2+ with KMnO4 / Mohr's salt; dichromate with Fe2+": {"react": ["redox_fe2_kmno4","redox_dichromate_fe"], "time": 60},
   "Preparation of lyophilic sols (starch, gelatin) and lyophobic sols (Fe(OH)3, arsenious sulphide - demo)": {"react": ["ppt_feoh3"], "time": 45},
   "Determine concentration of KMnO4 solution by titration against standard oxalic acid": {"react": ["redox_oxalate_kmno4"], "time": 50},
   "Vernier-calorimeter style determination of enthalpy of neutralisation of HCl with NaOH": {"react": ["ab_hcl_naoh","therm_neutralisation_pair"], "time": 45},
   "Effect of temperature on reaction rate of KIO3 and NaHSO3 (the iodine clock)": {"react": ["kin_clock_bisulphite"], "time": 45},
 },
 "Practical skills that are examined but rarely simulated": {
   "Cleaning and polishing a crucible / constant mass technique": {"app": ["crucible","pipeclay-triangle","desiccator"], "time": 20,
     "note": "two consecutive weighings within 0.005 g, not 'when it looks dry'"},
   "Using a pipette correctly": {"app": ["pipette_25"], "time": 15,
     "note": "rinse with the solution, fill above the ring, adjust with the forefinger not the thumb, drain and wait 15 s, do NOT blow out the residual drop unless the pipette is marked 'blow'"},
   "Filling and reading a burette, removing the air bubble": {"app": ["burette_50"], "time": 10,
     "note": "the bubble in the tip is the most common single source of a 0.3 mL error, which is bigger than the rest of the titration's uncertainty budget"},
   "Recording and reporting: concordant titres, uncertainties, and the 'do not fudge' rule": {"time": 10,
     "note": "an app that quietly gives the 'right answer' teaches the wrong skill; this dataset keeps tolerance fields so the app can be honest about error"},
 },
 "Common undergraduate / A-level additions": {
   "Preparation and analysis of an alum (double salt)": {"react": ["syn_alum","eq_hydrate_ind"], "time": 120},
   "Preparation of aspirin and its purity check (FeCl3 + melting point)": {"react": ["org_acetylation","org_fecl3_phenol"], "time": 120},
   "Steam distillation of an essential oil / bromobenzene": {"react": ["org_distillation_bp"], "time": 90},
   "Partition coefficient of an acid between water and an organic solvent": {"react": ["equ_distribution_law"], "time": 90},
   "Determination of the formula of a hydrated salt by heating": {"react": ["dec_cuso4","therm_crystallisation_water"], "time": 45},
   "Molar mass by gas collection (Mg + HCl) and the ideal gas law": {"react": ["dis_mg_hcl","elec_water_tension"], "time": 40},
   "Solubility product of calcium hydroxide by titration": {"react": ["ab_hcl_naoh"], "time": 60},
   "Kinetics by conductometry of saponification of ethyl acetate": {"react": ["org_hydrolysis_ester"], "time": 60},
   "Determine the cell constant and the conductivity of electrolytes": {"react": ["elec_conductivity","elec_conductivity_dilution"], "time": 45},
   "Electrolysis: verify Faraday's laws with a copper coulometer": {"react": ["elec_faraday_cu","elec_electroplating"], "time": 60},
   "Preparation of a coordination compound (cis-[Co(en)2Cl2]Cl / pot. trioxalato ferrate)": {"react": ["cx_cuso4_k4fecn"], "time": 120, "safety": "chrome/cobalt - a demonstration-grade prep"},
 },
}

# ------------------------------------------------------------------ troubleshooting
# The part of 'realism' that is never data and never UI: what goes wrong and why.
TROUBLESHOOTING = [
 ("your titration overshot", ["the burette tip still had an air bubble at the start", "you rinsed the conical flask with the analyte (which adds moles)", "you read the top of the meniscus for a dark solution and the bottom for a clear one", "you waited too long at the end point and the CO2 of the air pulled a phenolphthalein pink back"],
   "the fix: 0.05 mL resolution, same meniscus rule every time, rinse only the burette/pipette with the solution they hold, and swirl while adding, never while looking at the colour"),
 ("no crystals formed", ["you used too much solvent - a saturated solution hot is not a saturated solution cold if it started dilute", "the solution is supersaturated and needs a scratch below the liquid line with a glass rod, or a seed crystal", "impurities are holding the crystallisation back", "you cooled it too fast and got an oil out instead of crystals"],
   "the fix: evaporate to a smaller volume, scratch, seed, and cool slowly first then in ice"),
 ("the precipitate went through the paper", ["it was a colloid, not a precipitate - so digest it warm with a little electrolyte", "the paper pores were too coarse for the particle size", "you filled the cone too high and it went round the edge"],
   "the fix: add a few drops of electrolyte, warm, let it settle, decant first; use a slow/quantitative paper for fine crystalline solids"),
 ("your yield was over 100 %", ["the product is not dry - the solvent is counted as product", "coprecipitated mother liquor (salt) is in it", "you weighed the watch glass wrong"],
   "the fix: dry to constant mass and re-weigh; a yield above 100 % is always a measurement problem, never chemistry"),
 ("your yield was near zero", ["the compound stayed dissolved (the classic cold-solvent-misjudgement)", "you filtered before it crystallised", "you used an old reagent: Na2SO3, H2O2, Na2S2O3 and SnCl2 all fail silently"],
   "the fix: check the solubility at the temperature you actually reached; test your reagent on a known sample first"),
 ("the pH meter drifts and jumps", ["the bulb is dirty or dried out", "the reference junction is blocked so the circuit is intermittent", "the buffer solutions are old or the bottle was cross-contaminated", "the temperature was not compensated"],
   "the fix: store the bulb in KCl solution not distilled water, calibrate fresh each session (two points bracketing your sample), and rinse between samples with the sample itself for a cheap probe"),
 ("your electrochemistry reading is far from the textbook EMF", ["junction and internal resistance (a school voltmeter loads the cell)", "the concentrations are not 1 M and you did not use Nernst", "the electrodes are oxidised (Al, Zn, Fe all carry films)", "polarisation/bubbles on an electrode"],
   "the fix: use a high-impedance digital meter, clean the metals with emery, and compute the expected value at your actual concentrations - then the residual is overpotential, which is a real number worth reporting"),
 ("the gas collected over water gave the wrong moles", ["you forgot the aqueous tension (about 2.4 kPa at 20 C, i.e. 2.4 % of an atmosphere)", "you read the volume with the water levels unequal inside and outside (a few cm of water = a few percent)", "the gas is soluble in water (NH3, HCl, SO2, CO2 partly) and never should have been collected this way", "the apparatus leaked while cooling, and the syringe/friction offset the reading"],
   "the fix: subtract vapour pressure, match levels, rock the syringe plunger before reading, and choose the collection method from the gas's own properties"),
 ("the flame test was yellow no matter what", ["sodium is on everything - your hands, the water, the glass, the wire", "the nichrome loop was not clean", "the sample solution was concentrated to a degree that washes everything out"],
   "the fix: clean the loop in HCl until it burns colourless, use distilled water, and look through cobalt glass for potassium"),
 ("your enthalpy number was too small", ["you ignored the calorimeter's own heat capacity (a glass beaker holds about as much heat as 60-100 mL of water)", "the reaction was slow and the heat leaked away while it ran", "the acid/base was not the concentration you thought", "for combustion: incomplete burning shows as soot, and the soot IS your missing enthalpy"],
   "the fix: add the water equivalent of the vessel, plot temperature against time and extrapolate to the mixing moment, and use a lid"),
]

# added from the GHS Rev.9 statements actually used by the PubChem blocks in this
# warehouse. Codes that this dataset saw but whose wording cannot be stated with
# confidence are recorded as null with a reason - the app must print the code, never a
# sentence it is not sure about.
H_CODES.update({
 "H221": "Flammable gas", "H227": "Combustible liquid", "H228": "Flammable solid",
 "H261": "In contact with water releases flammable gases",
 "H272": "May intensify fire; oxidiser", "H304": "May be fatal if swallowed and enters airways",
 "H316": "Causes mild skin irritation", "H320": "Causes eye irritation",
 "H333": "May be harmful if inhaled", "H336": "May cause drowsiness or dizziness",
 "H351": "Suspected of causing cancer", "H361": "Suspected of damaging fertility or the unborn child",
 "H361d": "Suspected of damaging the unborn child", "H361f": "Suspected of damaging fertility",
 "H362": "May cause harm to a breast-fed child", "H402": "Harmful to aquatic life",
 "H412": "Harmful to aquatic life with long lasting effects",
 "H413": "May cause long lasting harmful effects to aquatic life",
})
H_CODES_UNVERIFIED = ["H281", "H303", "H305", "H313", "H341", "H371", "H261x"]

P_CODES.update({
 "P222": "Do not allow contact with dry material", "P223": "Keep away from combustible material",
 "P233": "Keep container tightly closed", "P234": "Keep in original container", "P235": "Keep cool",
 "P242": "Use explosion-proof electrical/ventilating/lighting/equipment",
 "P261": "Avoid breathing dust/fume/gas/mist/vapours/spray",
 "P262": "Do not get in eyes, on skin, or on clothing",
 "P263": "Avoid contact during pregnancy/while nursing",
 "P272": "Contaminated work clothing must not be allowed out of the workplace",
 "P282": "Wear cold insulating gloves and face shield",
 "P283": "Wear flame resistant/anti-static clothing",
 "P331": "Do NOT induce vomiting", "P332": "If skin irritation occurs: get medical advice/attention",
 "P333": "If skin irritation or rash occurs: get medical advice/attention",
 "P337": "If eye irritation persists: get medical advice/attention",
 "P338": "Rinse cautiously with water for several minutes",
 "P351": "Rinse with water for several minutes", "P352": "Wash with plenty of soap and water",
 "P353": "Rinse skin with water/shower", "P362": "Take off contaminated clothing and wash before reuse",
 "P363": "Wash contaminated clothing before reuse", "P364": "Wash before reuse",
 "P370": "In case of fire", "P375": "Fight fire from a distance using unattended methods",
 "P376": "Stop flow; if it can be done safely", "P377": "Eliminate all ignition sources",
 "P378": "Use water spray to cool", "P380": "Evacuate", "P381": "Eliminate all ignition sources if safe",
 "P390": "Absorb spillage to prevent material damage",
 "P402": "Store in a dry place", "P403": "Store in a well-ventilated place",
 "P404": "Store in a locked area", "P407": "Arrange stacks with gaps between them",
 "P410": "Protect from sunlight", "P413": "Bulk stock of combustible dust: keep cool",
 "P420": "Isolate area of emission; keep away from traffic",
 "P301": "IF SWALLOWED: (a combination phrase - read with the second code)",
 "P302": "IF ON SKIN: (combination phrase)", "P303": "IF ON SKIN (or hair): (combination phrase)",
 "P304": "IF INHALED: (combination phrase)", "P305": "IF IN EYES: (combination phrase)",
 "P306": "Remove immediately all contaminated clothing (combination phrase)",
 "P316": "Get medical attention immediately", "P317": "Get medical attention",
 "P318": "If eye irritation persists or worsens: get medical attention",
 "P319": "Get medical advice/attention if you feel unwell", "P320": "Specific treatment (see first aid on this label)",
 "P321": "See first aid on this label", "P334": "Under water while removing contact lenses",
 "P335": "Brush off dry material: do NOT use compressed air", "P336": "Keep calm",
 "P340": "Carry out respiratory resuscitation if not breathing", "P342": "Do NOT induce vomiting (combination)",
 "P354": "Do NOT dry or wipe; cover with a sterile dressing", "P360": "Rinse and wash eyes",
 "P361": "Remove/take off all contaminated clothing immediately",
 "P371": "In case of fire: do NOT use water", "P405": "Store under lock",
 "P308": "IF EXPOSED or concerned: get medical advice/attention",
 "P284": "Wear respiratory protection",
 "P203": "Remove contaminated clothing before reuse", "P244": "Keep stoppers and fittings clean and free of grease",
 "P264": "Wash hands and exposed skin thoroughly after handling", "P265": "Do not handle until all safety precautions have been read",
 "P261": "Avoid breathing dust/fume/gas/mist/vapours/spray",
})
# Codes the PubChem blocks referenced that this dataset will not paraphrase:
P_CODES_UNVERIFIED = ["P284", "P220x"]

# ------------------------------------------------------------------ non-graduated kit
# `app=` on a reaction names whatever the procedure needs. Most of it is graduated
# glassware (tables.GLASSWARE); the rest is listed here so the app can render a complete
# bench and so nothing in the data is left dangling.
ACCESSORIES = {
 "bunsen": ("burner", "the default heat source; blue cone, air hole open for the hottest flame"),
 "spirit-lamp": ("burner", "cooler and gentler than a Bunsen; the choice when a flame must not be fierce"),
 "blowpipe": ("burner", "concentrates the flame for dry-practical (blowpipe) assay on charcoal"),
 "blast-shield": ("safety", "face-height screen between the bench and the class for anything that may spit"),
 "fume-hood": ("safety", "the sash down to the working line, and face velocity checked, not assumed"),
 "fire-tray": ("safety", "a tray under anything hot or flammable so a spill stays inside one person's bench"),
 "tray": ("safety", "as fire-tray; the word a procedure uses when it means 'catch the spill'"),
 "tube": ("vessel", "a plain test tube; when a procedure says 'a tube' it means 5 mL of solution, not 50"),
 "splash-guard": ("safety", "a clear shield for the front of a bench when a reaction is run warm"),
 "ice-bath": ("temperature", "water plus ice, so about 0 C and better contact than loose ice"),
 "ice": ("consumable", "for the bath; a beaker of ice alone warms through in minutes"),
 "water-bath": ("temperature", "the gentle heat for anything under 100 C, and the only safe heat for ether"),
 "sand-bath": ("temperature", "for above 100 C without a flame under the flask"),
 "hot-plate": ("temperature", "no flame, but a hot plate still ignites ether vapour at its switch"),
 "pipeclay-triangle": ("support", "holds a crucible over a flame; replace when it cracks"),
 "ceramic-square": ("support", "the modern wire-gauze: spreads flame heat and does not conduct"),
 "charcoal-block": ("support", "the dry-practical furnace: a cavity holds a pinch of sample and reflects heat"),
 "tripod": ("support", "a tripod plus gauze is the standard 'heat a beaker' rig"),
 "test-tube": ("vessel", "about 20 mL; a reaction in a tube is a tenth of the reagent and a tenth of the risk"),
 "test-tubes": ("vessel", "plural of the above; racks hold 20-30"),
 "boiling-tube": ("vessel", "a long tube for heating liquids, clamped a third from the top, mouth away from faces"),
 "boiling-tubes": ("vessel", "see boiling-tube"),
 "hard-glass-tube": ("vessel", "for strong heating of solids; ordinary tube glass softens"),
 "dry-tube": ("vessel", "a tube stoppered while hot so nothing condenses back into the product"),
 "stoppered-tube": ("vessel", "for shaking two immiscible liquids; vent often"),
 "tilted-tube": ("vessel", "the 45-degree angle for gentle boiling so the surface wets evenly"),
 "delivery-tube": ("tubing", "bent glass tube for directing a gas; use a cork bore and wet the glass"),
 "delivery": ("tubing", "as delivery-tube"),
 "trough": ("collection", "the water trough for collecting gas over water"),
 "eudiometer": ("measurement", "a graduated tube for gas volumes; the only honest way to show 2:1 stoichiometry in a gas"),
 "gas-syringe": ("measurement", "100 mL syringe with low-friction plunger; rock it before reading"),
 "syringe": ("measurement", "see gas-syringe"),
 "two-syringes": ("measurement", "a sealed pair for pressure/equilibrium work such as NO2/N2O4"),
 "two-bottles": ("collection", "the two-bottle displacement method for a gas you cannot collect over water"),
 "woulff": ("safety", "a Woulff bottle is the trap that stops suck-back; every gas line that is heated needs one"),
 "kipp": ("generator", "a Kipp's apparatus makes a gas on demand and stops when the tap closes"),
 "inverted-funnel": ("collection", "the funnel held just under the surface for a soluble gas - it stops suck-back by breaking the seal"),
 "funnel": ("transfer", "a plain glass funnel; fluted filter paper in it drains faster"),
 "fluted-filter": ("filtration", "fluting a filter doubles the area and speeds a gelatinous precipitate"),
 "separating-funnel": ("separation", "vent upwards, then again after ten seconds; the pressure is real"),
 "sep-funnel": ("separation", "see separating-funnel"),
 "evaporating-dish": ("vessel", "a wide shallow basin for concentrating to crystallisation, not to dryness"),
 "evaporating-basin": ("vessel", "see evaporating-dish"),
 "round-bottom": ("vessel", "a round-bottom flask; the only shape that survives a vacuum"),
 "flask": ("vessel", "generic; for heating under vacuum, round-bottom only"),
 "beaker": ("vessel", "generic; a beaker is for holding, not measuring"),
 "beakers": ("vessel", "generic; a beaker is for holding, not measuring"),
 "jar": ("vessel", "a wide jar for the gas-in-jar tests"),
 "bottle": ("vessel", "a dropping or reagent bottle; the label and the cap, not the glass, is the safety feature"),
 "jar-test": ("measurement", "the 3-day BOD jar: fill to overflowing, no head space, keep in the dark at 20 C"),
 "column": ("separation", "a chromatography or fractionating column; packing and speed decide the separation"),
 "distillation": ("setup", "the whole rig; thermometer bulb level with the side arm"),
 "all-glass-distillation": ("setup", "no ground-glass grease where the product must not be contaminated"),
 "reflux": ("setup", "condenser vertical, water in at the bottom, and never a closed system"),
 "combustion-tube": ("vessel", "a hard-glass tube for burning a solid in a gas stream"),
 "combustion-boat": ("vessel", "the porcelain boat that carries a weighed solid into the flame"),
 "deflagrating-spoon": ("tool", "a long-handled spoon with a lid, for lowering a burning solid into a jar of gas"),
 "calorimeter": ("measurement", "a vessel whose own heat capacity must be known before any enthalpy is quoted"),
 "copper-calorimeter": ("measurement", "thin copper, light and conductive; its water equivalent is measured, not assumed"),
 "polystyrene-cup": ("measurement", "the school calorimeter: cheap insulation, and the lid is what makes it work"),
 "balance": ("measurement", "the only instrument that should be levelled before use; see glassware tolerances"),
 "conical": ("vessel", "the titration flask; swirl, never shake"),
 "burette": ("measurement", "rinse with the solution, purge the tip, read the meniscus at eye level"),
 "dropper": ("transfer", "a Pasteur pipette; never lay a rubber teat down on a bench"),
 "cotton-wool": ("consumable", "a plug that lets gas out and stops solid leaving - the classic 'is it a gas' tube"),
 "two-cotton-plugs": ("consumable", "the diffusion tube: plug both ends, and the ring forms where the two gases meet"),
 "thread": ("tool", "for lowering something into a jar so you can pull it out again"),
 "wire": ("tool", "copper or nichrome for the flame test; clean it in acid until the flame stays colourless"),
 "white-paper": ("tool", "the background for a colour change, and the surface a precipitate is judged against"),
 "white-tile": ("tool", "a spotting tile with a white bottom; the same reason"),
 "spotting-tile": ("tool", "a well in a tile lets a test run on five drops"),
 "thermometer": ("measurement", "bulb in the liquid, never on the glass; and know its tolerance"),
 "pH-probe": ("measurement", "calibrate with two buffers bracketing the sample; store the bulb in KCl, not water"),
 "pH-paper": ("measurement", "touch, do not dip - dipping leaches dye into the sample"),
 "strip": ("measurement", "a test strip; read it against the chart in daylight, not under a yellow lamp"),
 "limit-paper": ("measurement", "filter paper used to test a wash - 'washings neutral to litmus' is a procedure, not advice"),
 "indicator-gel": ("measurement", "an indicator immobilised in gel, so a gas colour change is not washed away"),
 "match": ("ignition", "the long match; for a gas jet the hand is behind the light, not over it"),
 "lighted-splint": ("ignition", "the pop test; a splint with a visible flame, not a glowing ember, for hydrogen"),
 "sparkler": ("ignition", "magnesium in a drawer away from water - it is its own fire risk"),
 "stopwatch": ("measurement", "for a rate: start it when the solutions meet, not when you put the flask down"),
 "iodometric": ("method", "the indirect iodine titration: excess iodide, then thiosulphate on the liberated iodine"),
 "conductivity-apparatus": ("measurement", "cell constant first, then the sample, then rinse - or the numbers drift"),
 "conductivity-meter": ("measurement", "see conductivity-apparatus; temperature compensation is not optional"),
 "Hofmann-voltameter": ("electrolysis", "the graduated double tube that shows 2:1 hydrogen to oxygen directly"),
 "diaphragm-cell-model": ("demo", "the model of the chlor-alkali cell, for showing why the membrane matters"),
 "flow-model": ("demo", "a visual of plug flow versus back-mixing in an industrial reactor"),
 "flow-reactor-model": ("demo", "see flow-model"),
 "orsat-model": ("demo", "the Orsat pipette train: CO2 absorbed in alkali, O2 in alkaline pyrogallol, CO in cuprous chloride"),
 "electrophoresis-tube": ("colloid", "a U-tube showing a sol migrating, which is how a charge on the particles is demonstrated"),
 "diffusion-tube": ("demo", "a long horizontal tube for showing diffusion, e.g. HCl and NH3 meeting as a ring"),
 "dark-room-lamp": ("safety", "the only light photography-grade paper tolerates; for silver-halide work the same rule applies"),
 "copper-strip": ("electrode", "clean it with emery until it is bright, or the cell voltage is a mystery"),
 "graphrod": ("electrode", "inert carbon; it will burn away in an oxidising anode compartment"),
 "Pt-electrode": ("electrode", "platinum, inert and expensive - the reason students are given carbon"),
 "Zn-rod": ("electrode", "amalgamate it or a school cell dies of local action within minutes"),
 "battery": ("source", "a steady low-voltage DC supply; a 9 V block discharges in minutes under electrolysis current"),
 "voltmeter": ("measurement", "a high-impedance digital meter, or an EMF reading is a load reading"),
 "ammeter": ("measurement", "in series; without it a 'constant current' is a wish"),
 "salt-bridge": ("electrochem", "filter paper soaked in KNO3 or a tube of agar; never a metal wire"),
 "inverted-funnel-water": ("collection", "gas collection over water with the funnel rim just under the surface"),
 "pipeclay-pipe": ("support", "as pipeclay-triangle"),
 "blow-dryer": ("drying", "for the outside of a crucible; the inside must cool in a desiccator"),
 "desiccator": ("drying", "the only way to cool something you are about to weigh, or it drinks water while hot"),
 # --- the rest of what KITS and the reaction records ask for, added so that a kit can be
 # --- assembled from the register alone. None of these is measured, so none carries a
 # --- tolerance, and that is a fact about the object rather than a missing number.
 "SDS_binder": ("setup", "the ring of safety data sheets the inspectors ask for; a lab that cannot produce them has not read what it stores"),
 "Cu-strip": ("electrode", "copper foil or strip, emeryed and degreased before it goes in the solution, or the potential you read belongs to the oxide"),
 "battery-lead": ("tubing", "insulated leads with crocodile clips and 4 mm plugs, which is what makes a school cell safe to touch"),
 "boiling-chips": ("consumable", "porous chips, added while the liquid is cold; dropped into a liquid already at its boil they are a nucleation bomb"),
 "brush": ("tool", "a long-haired tube brush, twisted not dragged, and never down the inside of a graduated tube you still intend to read"),
 "capillary-tubes": ("consumable", "sealed-end capillaries for a melting point and for spotting a plate; one drop each, and never the same capillary twice"),
 "chrom-chamber": ("setup", "a lidded jar with solvent in the bottom, left to saturate before the plate goes in, or the front runs crooked and the Rf means nothing"),
 "clamp": ("support", "the boss clamp takes the neck of the flask, never the bulb, and never the calibration ring of a volumetric"),
 "cobalt-glass": ("observation", "blue glass that takes the yellow out of a sodium flame so the lilac of potassium can be seen through it"),
 "cork-bore": ("tool", "corkscrew borers, driven from the wide end with the cork on a board, and wetted before any glass is pushed through them"),
 "dropping_bottle": ("vessel", "a wash bottle with a dropper top, which is how one person adds a reagent dropwise and watches the tube at the same time"),
 "extinguisher": ("safety", "CO2 or dry powder for a bench fire and for the electrical panel; water is only for paper and wood, and only when the fire is that small"),
 "eye_wash": ("safety", "a plumbed station or a dedicated bottle that will run for fifteen minutes; the clock starts when the chemical touches the eye"),
 "filter-paper": ("consumable", "qualitative paper, about 10 micron retention; if the residue is going to be weighed it is the ashless quantitative paper that is wanted, at ten times the price"),
 "fire_blanket": ("safety", "for clothing alight: wrap and stop the person; it is not a substitute for the shower when the burn is on the torso"),
 "first_aid_box": ("safety", "burn gelplasters, sterile gauze, plasters, eyewash, and nothing with a pharmacological action - a school lab is not where tablets are handed out"),
 "glass-plate": ("tool", "the 5 by 10 cm square a dropping reaction is done on, and the window a flame test is read against; cheaper than a tile and easier to clean than one"),
 "glass_rod": ("tool", "a stirring rod with fire-polished ends, since a cut end takes the skin off a fingertip; also the way to move one drop onto paper"),
 "heating-mantle": ("heat", "an electric mantle for any flammable liquid, because a Bunsen under a flask of ether is how laboratories burn down"),
 "lid": ("cover", "a watch glass or beaker lid slid across the top: it keeps splashing in and dust out, and it does not seal a vessel you are about to heat"),
 "nichrome-loop": ("tool", "the loop for a flame test, dipped in concentrated HCl and heated until it gives no colour of its own, which is the whole skill of the test"),
 "receiver": ("vessel", "the flask the distillate lands in; a receiver sealed at the top turns a still into a pressure vessel with a burner under it"),
 "ring": ("support", "the iron ring on the stand, under a gauze or a funnel; a ring set too high leaves a funnel hanging on its own stem"),
 "round-bottom-flask": ("vessel", "for anything heated under reflux or in a mantle; a conical flask in that position has a flat spot that will crack"),
 "spectroscope": ("observation", "a prism or grating viewer for the lines a flame gives: the sodium D pair at 589 nm is obvious in it and hard to see beside a bright flame"),
 "sprayer": ("tool", "an atomiser for a developing agent or for dampening paper; rinsed with acetone afterwards or the next plate is contaminated by this one"),
 "stand": ("support", "the retort stand and boss: heavy base flat on the bench, clamp above the vessel, and the whole assembly behind the glass so a knock takes the clamp"),
 "tongs": ("tool", "crucible tongs for a crucible and beaker tongs for a beaker; the metal ones will crack a beaker and the wooden ones will not hold a red-hot crucible"),
 "uv-lamp": ("observation", "254 nm or 365 nm to see what a plate is showing; the lamp comes with goggles, and neither half of that sentence is optional"),
 "wash_bottle": ("vessel", "distilled water unless the procedure says otherwise, and the reason a quantitative transfer is quantitative: rinse the beaker down the rod three times into the funnel"),
 "waste_containers": ("safety", "labelled, in date and kept apart: halogenated solvent, non-halogenated solvent, aqueous heavy metal, acid, alkali; nothing goes down a drain because it smells harmless"),
 "thiele-tube": ("heat", "a boiling tube with a bulb blown in it, the classic melting-point bath: the acid concentrates in the bulb and the top stays cool enough to hold"),
 "white-paper-cross": ("observation", "the card with the black cross under the flask for the thiosulfate-and-acid clock; what is timed is the cross disappearing, not the solution changing"),
}
# Things an `app=` field sometimes names that are consumables or reagents, not apparatus.
MATERIALS = {"limewater", "starch", "concentrated-H2SO4", "pH-10-buffer", "organic-solvent",
             "ammonia-solution", "saturated-K2Cr2O7", "iodine-solution"}


# ------------------------------------------------------------------- apparatus kits
KITS = {
 "everyday-chemistry": ["beaker_100","beaker_250","conical_250","test_tube","funnel_glass","glass_rod","watchglass","dropping_bottle","brush","safety_shield"],
 "titration": ["burette_50","pipette_25","pipette_10","conical_250","volumetric_250","beaker_100","funnel_glass","wash_bottle","white-tile"],
 "gas-generation-and-collection": ["boiling_tube","delivery-tube","trough","eudiometer","gas_syringe","woulff","kipp","cork-bore","retort_stand"],
 "salt-analysis": ["spotting_tile","test_tube","boiling_tube","centrifuge_tube","funnel_glass","bunsen","nichrome-loop","cobalt-glass","spectroscope","tongs"],
 "electrochemistry": ["voltmeter","ammeter","beaker_100","salt-bridge","Pt-electrode","graphrod","Cu-strip","Zn-rod","filter-paper","battery-lead"],
 "distillation-and-reflux": ["round-bottom-flask","distillation_head","liebig_condenser","fractionating_column","receiver","thermometer_110","heating-mantle","boiling-chips","retort_stand","clamp"],
 "extraction-and-chromatography": ["sep-funnel","stand","ring","beaker_100","capillary-tubes","chrom-chamber","glass-plate","sprayer","uv-lamp"],
 "thermochemistry": ["polystyrene-cup","thermometer_bei","balance_pan","beaker_250","stopwatch","lid","measuring_cyl_250"],
 "kinetics": ["gas_syringe","stopwatch","conical_100","thermometer_110","spotting-tile","beaker_100","white-paper-cross","water-bath"],
 "first-aid-safety": ["goggles","nitrile_gloves","lab_coat","eye_wash","spill_kit","fire_blanket","extinguisher","first_aid_box","waste_containers","SDS_binder"],
}
