# Explicit PubChem search names where auto-naming can't win (double salts, hydrates,
# solutions). The fetcher verifies every hit by formula + molar mass, so these are
# only suggestions - a wrong one here cannot corrupt the dataset.
PUBCHEM_NAME = {
 "mohrsalt": "iron ammonium sulfate",
 "kalsulfate": "potassium aluminum sulfate",
 "na2co3": "sodium carbonate",
 "nahco3": "sodium bicarbonate",
 "cuso4": "copper sulfate pentahydrate",
 "caso4": "calcium sulfate",
 "mgso4": "magnesium sulfate",
 "znso4": "zinc sulfate",
 "feso4": "iron(2+) sulfate",
 "fecl3": "iron trichloride",
 "fecl2": "ferrous chloride",
 "feno3_3": "ferric nitrate",
 "cacl2": "calcium chloride",
 "bacl2": "barium chloride",
 "mgcl2": "magnesium chloride",
 "alcl3": "aluminum chloride",
 "sncl2": "tin dichloride",
 "pbno3_2": "lead dinitrate",
 "pbno3_2aq": "lead dinitrate",
 "agno3": "silver nitrate",
 "agno3aq": "silver nitrate",
 "k2cr2o7": "potassium dichromate",
 "k2cro4": "potassium chromate",
 "na2cro4": "sodium chromate",
 "kmno4": "potassium permanganate",
 "na2s2o3": "sodium thiosulfate",
 "na2so3": "sodium sulfite",
 "naso3": "sodium bisulfite",
 "na2s": "sodium sulfide",
 "na2s2o4": "sodium dithionite",
 "k4fecn6": "potassium ferrocyanide",
 "k3fecy": "potassium ferricyanide",
 "na2hpo4": "disodium phosphate",
 "nah2po4": "monosodium phosphate",
 "na3po4": "trisodium phosphate",
 "ca3po4": "calcium phosphate",
 "nh42so4": "ammonium sulfate",
 "nh4no3": "ammonium nitrate",
 "nh4cl": "ammonium chloride",
 "nh4scn": "ammonium thiocyanate",
 "nh42c2o4": "ammonium oxalate",
 "oxalicacid": "oxalic acid",
 "na2c2o4": "sodium oxalate",
 "k2c2o4": "potassium oxalate",
 "ni2aq": "nickel nitrate",
 "niso4": "nickel sulfate",
 "nicl2": "nickel chloride",
 "coso4": "cobalt sulfate",
 "cocl2": "cobalt chloride",
 "mnso4": "manganese sulfate",
 "mncl2": "manganese chloride",
 "cdso4": "cadmium sulfate",
 "hgcl2": "mercury dichloride",
 "hg2cl2": "mercurous chloride",
 "hgo": "mercury oxide",
 "bi2o3aq": "bismuth subnitrate",
 "crcl3aq": "chromium trichloride",
 "crno3s": "chromium nitrate",
 "caso4aq": "calcium sulfate",
 "caco3": "calcium carbonate",
 "cao": "calcium oxide",
 "caoh2": "calcium hydroxide",
 "sio2": "silicon dioxide",
 "na2sio3": "sodium silicate",
 "h2sio3": "silicic acid",
 "h3bo3": "boric acid",
 "na2b4o7": "borax",
 "kf": "potassium fluoride",
 "na2edta": "disodium edetate",
 "kno3": "potassium nitrate",
 "nano3": "sodium nitrate",
 "nano2": "sodium nitrite",
 "naclo3": "sodium chlorate",
 "kclo3": "potassium chlorate",
  "urea": "urea",
 "thiourea": "thiourea",
 "glycine": "glycine",
 "alanyl": "alanine",
 "sucrose": "sucrose",
 "glucose": "glucose",
 "fructose": "fructose",
 "lactose": "lactose",
 "starch_powder": "starch",
 "cellulose": "cellulose",
 "citric": "citric acid",
 "tartaric": "tartaric acid",
 "ascorbic": "ascorbic acid",
 "lactic": "lactic acid",
 "malonic": "malonic acid",
 "succinic": "succinic acid",
 "salicylic": "salicylic acid",
 "benzoicacid": "benzoic acid",
 "phthalicanh": "phthalic anhydride",
 "saccharin": "saccharin",
 "catechol": "catechol",
 "resorcinol": "resorcinol",
 "cresol": "cresol",
 "napthalene": "naphthalene",
 "anthracene": "anthracene",
 "acetophenone": "acetophenone",
 "benzophenone": "benzophenone",
 "benzaldehyde": "benzaldehyde",
 "nitrobenzene": "nitrobenzene",
 "aniline": "aniline",
 "phenol": "phenol",
 "amylacetate": "isoamyl acetate",
 "ethylacetate": "ethyl acetate",
 "methylacetate": "methyl acetate",
 "acetaldehyde": "acetaldehyde",
 "formaldehyde": "formaldehyde",
 "propionic": "propionic acid",
 "butyric": "butyric acid",
 "propan2ol": "isopropanol",
 "butan2olt": "tert-butanol",
 "ethersolv": "diethyl ether",
 "petrolether": "petroleum ether",
 "hexane": "n-hexane",
}